### PR TITLE
homework1: Belaid Ruman

### PR DESCRIPTION
**Pull request by Belaid86**
### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle)
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks
- [x] my PR made from the fork feature branch to maxim homework# branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

### CODE REVIEW

**Comment by Belaid86** [comment]
the homework 1 is completed

**Review by belovmd — CHANGES_REQUESTED** [review]
Please add additional tasks for evaluating this homework. you can find evaluation criterias [here](https://github.com/belovmd/it-academy-winter-2020/blob/master/hw_review/homework1.md)

**Comment by Belaid86** [comment]
The Job is done Boss-)))

**Review by belovmd — APPROVED** [review]
missed tasks description
PR name contradicts our guidelines

+0.5

**Pull request closed without merging**
